name: CustomRoleplayMessages
version: '${project.version}'
main: com.alex22sv.customroleplaymessages.CustomRoleplayMessages
api-version: 1.18
authors: [ Alex22_SV ]
description: Mensajes de roleplay con autores personalizados.
commands:
  admin:
    usage: /admin [jugador] <mensaje>
    description: Envía mensajes como 'ADMIN'.
  autor:
    usage: /autor <nombre del autor> [jugador] <mensaje>
    description: Envía mensajes con un autor personalizado.
  dioses:
    usage: /dioses [jugador] <mensaje>
    description: Envía mensajes como 'DIOSES'.
  elmapache:
    usage: /elmapache [jugador] <mensaje>
    description: Envía mensajes como 'EL MAPACHE'.
  eltopo:
    usage: /eltopo [jugador] <mensaje>
    description: Envía mensajes como 'EL TOPO'.
  kaspar:
    usage: /kaspar [jugador] <mensaje>
    description: Envía mensajes como 'EL HECHICERO KASPAR'
  noticia:
    usage: /noticia [jugador] <mensaje>
    description: Envía mensajes como '¡NOTICIA DE ÚLTIMA HORA!'
  servidor:
    usage: /servidor [jugador] <mensaje>
    description: Envía mensajes como 'SERVIDOR'.


