name: CustomRoleplayMessages
version: '${project.version}'
main: com.alex22sv.customroleplaymessages.CustomRoleplayMessages
api-version: 1.18
authors: [ Alex22_SV ]
description: Mensajes de roleplay con autores personalizados.
commands:
  admin:
    usage: /admin [jugador] <mensaje>
    description: Envía mensajes como 'Admin'.
  autor:
    usage: /autor <nombre del autor> [jugador] <mensaje>
    description: Envía mensajes con un autor personalizado.
  dioses:
    usage: /dioses [jugador] <mensaje>
    description: Envía mensajes como 'DIOSES'.
  hermandad:
    usage: /hermandad [jugador] <mensaje>
    description: Envía mensajes como 'La Hermandad'.
  mapache:
    usage: /topo [jugador] <mensaje>
    description: Envía mensajes como 'Señor Mapache'.
  topo:
    usage: /topo [jugador] <mensaje>
    description: Envía mensajes como 'El Topo'.
  kaspar:
    usage: /kaspar [jugador] <mensaje>
    description: Envía mensajes como 'Hecichero Kaspar'
  noticia:
    usage: /noticia [jugador] <mensaje>
    description: Envía mensajes como '¡NOTICIA DE ÚLTIMA HORA!'
  servidor:
    usage: /servidor [jugador] <mensaje>
    description: Envía mensajes como 'Servidor'.


